### ISSUE TITLE
Spots in DB

### ISSUE THREAD

**Issue by nikdo** [nikdo/wind-alert#28]
All spots from wind-freaks are stored in a database and served to the client for selection.

**Comment by nikdo** [comment]
# Tasks

- [x] purchase Digital Ocean VPS
- [x] set up MongoDB on Digital Ocean
- [x] run wfx locally to investigate what I have
- [ ] import spots to Digital Ocean MongoDB
- [ ] fetch spots from MongoDB
- [ ] add notes about database to README
